<?php

namespace ContainerZ7qf1qi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B7bQKA3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B7bQKA3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B7bQKA3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avtoRepository' => ['privates', 'App\\Repository\\AvtoRepository', 'getAvtoRepositoryService', true],
        ], [
            'avtoRepository' => 'App\\Repository\\AvtoRepository',
        ]);
    }
}
