<?php

namespace ContainerZ7qf1qi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X0srhU1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X0srhU1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X0srhU1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doct' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'doct' => '?',
        ]);
    }
}
