<?php

namespace ContainerFpfuGxV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PIz4LY2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pIz4LY2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pIz4LY2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AppController::index' => ['privates', '.service_locator.B7bQKA3', 'get_ServiceLocator_B7bQKA3Service', true],
            'App\\Controller\\CRUDController::deleteProduct' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.X0srhU1', 'get_ServiceLocator_X0srhU1Service', true],
            'App\\Controller\\CartController::updateQuantity' => ['privates', '.service_locator.X0srhU1', 'get_ServiceLocator_X0srhU1Service', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AppController:index' => ['privates', '.service_locator.B7bQKA3', 'get_ServiceLocator_B7bQKA3Service', true],
            'App\\Controller\\CRUDController:deleteProduct' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.X0srhU1', 'get_ServiceLocator_X0srhU1Service', true],
            'App\\Controller\\CartController:updateQuantity' => ['privates', '.service_locator.X0srhU1', 'get_ServiceLocator_X0srhU1Service', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AppController::index' => '?',
            'App\\Controller\\CRUDController::deleteProduct' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::updateQuantity' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AppController:index' => '?',
            'App\\Controller\\CRUDController:deleteProduct' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:updateQuantity' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
