<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFpfuGxV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFpfuGxV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFpfuGxV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFpfuGxV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFpfuGxV\App_KernelDevDebugContainer([
    'container.build_hash' => 'FpfuGxV',
    'container.build_id' => '86461c20',
    'container.build_time' => 1707141036,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFpfuGxV');
